source/src/java/com/wpsj/model/ProductFinderBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wpsj.model;

import com.wpsj.da.ProductDataAcess;
import com.wpsj.entity.Product;
import java.util.List;

/**
 *
 * @author Puarinnnn
 */
public class ProductFinderBean {

    private String keyword;

   
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public List<Product> getProducts(){
        return new 
            ProductDataAcess().getProductsByName(keyword);
    }
  
}

source/src/java/LoginServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Puarinnnn
 */
public class LoginServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet LoginServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet LoginServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        request.getRequestDispatcher("navigation.html").include(request, response);
        
        String name = request.getParameter("username");
        String password = request.getParameter("password");
        
        if(name.equals(password)){
            out.print("Welcome," +name);
            HttpSession session =request.getSession();
            session.setAttribute("name",name);
            Cookie cookie = new Cookie("name",name);
            response.addCookie(cookie);
        }else{
            out.print("Username and password error!!!");
            request.getRequestDispatcher("login.jsp").include(request, response);
        }
        out.close();
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

source/web/Edit.jsp
<%-- 
    Document   : Edit
    Created on : Mar 29, 2018, 10:54:11 PM
    Author     : Puarinnnn
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Thêm mới</h1>
        <form action="ProductEdit">
            <label>ID:</label><input name="id" type="text"/><br>
            <label>NAME:</label><input name="name" type="text"/><br>
            <label>DESC:</label><input name="desc" type="text"/><br>
            <input value="Save" type="submit"/>
        </form>
    </body>
</html>

source/web/add.jsp
<%-- 
    Document   : add
    Created on : Mar 29, 2018, 5:24:55 PM
    Author     : Puarinnnn
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <form action="AddPost">
            <label>ID: </label><input name="id" type="text"/><br>
            <label>Name: </label><input name="name" type="text"/><br>
            <label>ID: </label><input name="desc" type="text"/><br>
            <input value="Save" type="submit"/>
            
        </form>
    </body>
</html>

source/web/login.jsp
<%-- 
    Document   : login
    Created on : Mar 30, 2018, 1:04:20 AM
    Author     : Puarinnnn
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <style>
            .input{height: 20px;width: 250px;margin-bottom: 5px;}
        </style>
    </head>
    <body>
        <form action="LoginServlet" method="POST">
            Name:<br><input class="input" type="text" name="name"/><br>
            Pass:<br><input class="input" type="password" name="password"/><br>
            <input styte="width:100px;height:24px;margin-top:15px;" type="submit" value="login"/>
        </form>
    </body>
</html>

source/web/result.jsp
<%-- 
    Document   : result
    Created on : Mar 29, 2018, 2:57:13 PM
    Author     : Puarinnnn
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>List Product</title>
    </head>
    <h1>List Product!</h1>
    <a href="search.jsp">Search</a>
    <jsp:useBean class="com.wpsj.model.ProductFinderBean" id="finder" scope="request"/>
    <a href="AddProduct">Add</a>
    <table>
        <tr>
            <td>Id</td>
            <td>name</td>
            <td>Description</td>
        </tr>
        <c:forEach items="${finder.products}" var="product">
            <tr>
                <td><c:out value="${product.id}"/></td>
                <td><c:out value="${product.name}"/></td>
                <td><c:out value="${product.desc}"/></td>
                <td><a href="ProductEdit?name=${product.name}">Edit</a></td>
                <td><a href="DeleteProduct?pro_name=${product.name}">Delete</a>
            </tr>
        </c:forEach>
            
    </table>
    
</html>

source/web/search.jsp
<%-- 
    Document   : search
    Created on : Mar 29, 2018, 2:57:25 PM
    Author     : Puarinnnn
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Shopping!</title>
    </head>
    <body>
        <h1>Product List</h1>
        <form action="ProductFinder">
            <span style="color: red;">
                <c:out value="${param.msg}"/>
            </span>
            <input name="name"/><input type="submit"/>
        </form>
    </body>
</html>